### ISSUE TITLE
Error during ERC20 'FrogToken'  deployment via Remix ( VM London and Linea Sepolia)

### ISSUE THREAD

**Issue by scripnichenko** [Venture-Miner/Linea-Dev-Cook-Off-Mini-Bootcamp#3]
## Problem
Given a code snippet from[ Part1 Tutorial](https://github.com/Venture-Miner/Linea-Dev-Cook-Off-Mini-Bootcamp/blob/main/README.md#using-tokens)

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol";

contract FrogToken is ERC20, ERC20Permit {
    constructor() ERC20("FrogToken", "FROG") ERC20Permit("FrogToken") {
        _mint(msg.sender, 1000 * 10 ** decimals());
    }
}
```

## 1. Attempt to deploy to **Local (Remix VM London)**

Error: 
```
[vm]from: 0x5B3...eddC4to: FrogToken.(constructor)value: 0 weidata: 0x610...40033logs: 0hash: 0x318...a3cf2
creation of FrogToken errored: Error occurred: invalid opcode.

invalid opcode
	
	The execution might have thrown OR the EVM version used by the selected environment is not compatible with the compiler EVM version.
```
Debug the transaction to get more information.

## 2. Attempt to deploy to **Injected Provider - Metamask**

Error: 

<img width="555" alt="image" src="https://github.com/Venture-Miner/Linea-Dev-Cook-Off-Mini-Bootcamp/assets/4344096/28556f46-525b-46e1-8103-0c2dec478c2e">

After accepting next error appears: 

<img width="1422" alt="image" src="https://github.com/Venture-Miner/Linea-Dev-Cook-Off-Mini-Bootcamp/assets/4344096/be74ee87-e087-4cf7-afda-b2dbd612274f">

**Comment by MatheusDaros** [comment]
Hello @scripnichenko 

Thanks for opening this issue.
We had this problem in our lesson as well, and we did not have enought time to fix it live.
For using solidity version `0.8.19` we can't use the recent versions of OpenZeppelin Contracts, that require solidity `0.8.20` or above. So in our case we would need to use older versions of OpenZeppelin Contracts to import the token contracts to use in our token.

The fixed code would look like this:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v4.9/contracts/token/ERC20/ERC20.sol";
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v4.9/contracts/token/ERC20/extensions/ERC20Permit.sol";

contract FrogToken is ERC20, ERC20Permit {
    constructor() ERC20("FrogToken", "FROG") ERC20Permit("FrogToken") {
        _mint(msg.sender, 1000 * 10 ** decimals());
    }
}
```

Notice how we're specifying the branch `release-v4.9` when importing, instead of picking the default that would be the `latest` release.

**Comment by scripnichenko** [comment]
Works now! 
Thanks, @MatheusDaros for info.

<img width="1435" alt="image" src="https://github.com/Venture-Miner/Linea-Dev-Cook-Off-Mini-Bootcamp/assets/4344096/964945d5-1f8e-4d86-b88f-d1a398d589bd">

**Comment by mpereyras** [comment]
![image](https://github.com/Venture-Miner/Linea-Dev-Cook-Off-Mini-Bootcamp/assets/105330338/3b20d396-2993-4b20-a4fe-9f2ed9bfbdd1)
I get a gas error, so I put the version directly: pragma solidity 0.8.19;
