### ISSUE TITLE
The command is not working: yarn chain

### ISSUE THREAD

**Issue by yurkko** [Venture-Miner/Linea-Dev-Cook-Off-Mini-Bootcamp#5]
![image](https://github.com/Venture-Miner/Linea-Dev-Cook-Off-Mini-Bootcamp/assets/107958804/950c4f8f-3a46-4b7e-85ed-4bd76b99a5b8)
After I wrote this command yarn chain, I got an error

**Comment by MatheusDaros** [comment]
Hello @Yurkko 
Could you provide some more info on how to reproduce this issue?
Does this happen when installing other projects with yarn as well, or just this one?
